<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1481" started-at="2018-05-04T12:21:49Z" finished-at="2018-05-04T12:21:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1481" started-at="2018-05-04T12:21:49Z" finished-at="2018-05-04T12:21:50Z">
      <class name="com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt">
        <test-method status="PASS" signature="CheckSuiteSkip()[pri:0, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="CheckSuiteSkip" is-config="true" duration-ms="2996" started-at="2018-05-04T17:51:46Z" finished-at="2018-05-04T17:51:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckSuiteSkip -->
        <test-method status="PASS" signature="checkTestSkip()[pri:0, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="checkTestSkip" is-config="true" duration-ms="1288" started-at="2018-05-04T17:51:49Z" finished-at="2018-05-04T17:51:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTestSkip -->
        <test-method status="FAIL" signature="toSelectOrgForPerformingAutomationTests(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="toSelectOrgForPerformingAutomationTests" duration-ms="16" started-at="2018-05-04T17:51:50Z" data-provider="getData" finished-at="2018-05-04T17:51:50Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: toSelectOrgForPerformingAutomationTests([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)DO NOT TOUCH AUTOMATION EMP 108,(java.lang.String)A  All other employees,(java.lang.String)12000.0,(java.lang.String)Monthly,(java.lang.String)DONT TOUCH AUTO COURTORDERS EMPLOYER,(java.lang.String)COURTORDERS_Payroll,(java.lang.String)September-2018,(java.lang.String)Payroll Suite CourtOrder AEO1971civildebt201819.xlsx,(java.lang.String),(java.lang.String)Need to create the Report in the framework itself,(java.lang.String)2,(java.lang.String)Current pay run,(java.lang.String)0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: toSelectOrgForPerformingAutomationTests([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)DO NOT TOUCH AUTOMATION EMP 108,(java.lang.String)A  All other employees,(java.lang.String)12000.0,(java.lang.String)Monthly,(java.lang.String)DONT TOUCH AUTO COURTORDERS EMPLOYER,(java.lang.String)COURTORDERS_Payroll,(java.lang.String)September-2018,(java.lang.String)Payroll Suite CourtOrder AEO1971civildebt201819.xlsx,(java.lang.String),(java.lang.String)Need to create the Report in the framework itself,(java.lang.String)2,(java.lang.String)Current pay run,(java.lang.String)0]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1278)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toSelectOrgForPerformingAutomationTests -->
        <test-method status="SKIP" signature="toSetEmployeesNICategory(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="toSetEmployeesNICategory" duration-ms="0" started-at="2018-05-04T17:51:50Z" data-provider="getData" depends-on-methods="com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt.toSelectOrgForPerformingAutomationTests" finished-at="2018-05-04T17:51:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCourtOrderAEO1971civildebt.toSetEmployeesNICategory(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCourtOrderAEO1971civildebt.toSetEmployeesNICategory(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toSetEmployeesNICategory -->
        <test-method status="SKIP" signature="setEmployeesAnnualSalaryAndPayfrequency(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="setEmployeesAnnualSalaryAndPayfrequency" duration-ms="0" started-at="2018-05-04T17:51:50Z" data-provider="getData" depends-on-methods="com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt.toSetEmployeesNICategory" finished-at="2018-05-04T17:51:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCourtOrderAEO1971civildebt.setEmployeesAnnualSalaryAndPayfrequency(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCourtOrderAEO1971civildebt.setEmployeesAnnualSalaryAndPayfrequency(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setEmployeesAnnualSalaryAndPayfrequency -->
        <test-method status="FAIL" signature="toReportTestResult()[pri:0, instance:com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt@42dafa95]" name="toReportTestResult" is-config="true" duration-ms="0" started-at="2018-05-04T17:51:50Z" finished-at="2018-05-04T17:51:50Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.test.xcdhr.Salesforce_Core_Framework1.testBase.TestBase.closeBrowser(TestBase.java:1140)
	at com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt.toReportTestResult(TestCourtOrderAEO1971civildebt.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toReportTestResult -->
      </class> <!-- com.testcase.xcdhr.Salaesforce_Core_Framework1.hrms_payroll.TestCourtOrderAEO1971civildebt_Scenario.TestCourtOrderAEO1971civildebt -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
